-- Stage 1.5 shared Postgres schema.
-- Core agent tables plus calibrated read views for the web app.

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  tier INTEGER NOT NULL,
  enabled INTEGER NOT NULL,
  warm_path INTEGER NOT NULL,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS job_sources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  source_type TEXT NOT NULL,
  source_key TEXT NOT NULL,
  source_url TEXT NOT NULL,
  parser_version TEXT NOT NULL,
  health_status TEXT NOT NULL DEFAULT 'disabled',
  last_success_at TEXT,
  expected_volume_min INTEGER,
  UNIQUE(company_id, source_type, source_key)
);

CREATE TABLE IF NOT EXISTS source_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_source_id INTEGER NOT NULL REFERENCES job_sources(id),
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  status TEXT NOT NULL,
  http_status INTEGER,
  fetched_count INTEGER NOT NULL,
  new_count INTEGER NOT NULL,
  changed_count INTEGER NOT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  error_summary TEXT
);

CREATE TABLE IF NOT EXISTS job_postings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  source_id INTEGER NOT NULL REFERENCES job_sources(id),
  source_job_id TEXT NOT NULL,
  canonical_key TEXT NOT NULL,
  title TEXT NOT NULL,
  locations_json TEXT NOT NULL,
  department TEXT,
  employment_type TEXT,
  description_text TEXT NOT NULL,
  source_url TEXT NOT NULL,
  posted_at TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  raw_payload_hash TEXT NOT NULL,
  availability_state TEXT NOT NULL,
  missing_successful_scan_count INTEGER NOT NULL DEFAULT 0,
  UNIQUE(source_id, source_job_id)
);

CREATE TABLE IF NOT EXISTS role_evaluations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_posting_id INTEGER NOT NULL REFERENCES job_postings(id),
  profile_version_id TEXT NOT NULL,
  location_policy_version_id TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  model_version TEXT NOT NULL,
  input_hash TEXT NOT NULL,
  evaluation_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(job_posting_id, input_hash, model_version)
);

CREATE TABLE IF NOT EXISTS evaluation_skips (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_posting_id INTEGER NOT NULL REFERENCES job_postings(id),
  input_hash TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(job_posting_id, input_hash, reason)
);

CREATE TABLE IF NOT EXISTS opportunity_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_posting_id INTEGER NOT NULL UNIQUE REFERENCES job_postings(id),
  state TEXT NOT NULL,
  decision_reason TEXT,
  reviewed_at TEXT,
  snooze_until TEXT
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  sent_at TEXT NOT NULL,
  status TEXT NOT NULL,
  error_summary TEXT
);

CREATE TABLE IF NOT EXISTS app_allowed_users (
  email TEXT PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_job_sources_company ON job_sources(company_id);
CREATE INDEX IF NOT EXISTS idx_source_runs_source ON source_runs(job_source_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_job_postings_source ON job_postings(source_id, source_job_id);
CREATE INDEX IF NOT EXISTS idx_job_postings_open ON job_postings(availability_state);
CREATE INDEX IF NOT EXISTS idx_role_evaluations_job_latest
  ON role_evaluations(job_posting_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_role_evaluations_model
  ON role_evaluations(model_version);
CREATE INDEX IF NOT EXISTS idx_reviews_state ON opportunity_reviews(state);

DROP VIEW IF EXISTS current_opportunity_evaluations;
DROP VIEW IF EXISTS current_calibrated_role_evaluations;

CREATE VIEW current_calibrated_role_evaluations
WITH (security_invoker = true) AS
SELECT re.*
FROM role_evaluations re
WHERE re.id = (
  SELECT MAX(latest.id)
  FROM role_evaluations latest
  WHERE latest.job_posting_id = re.job_posting_id
    AND latest.model_version LIKE '%|hybrid\_claude\_v2' ESCAPE '\'
    AND latest.model_version NOT ILIKE '%deterministic_fallback%'
    AND COALESCE(
      lower(latest.evaluation_json::jsonb #>> '{provenance,fallback_quality}'),
      'false'
    ) <> 'true'
    AND COALESCE(
      lower(latest.evaluation_json::jsonb #>> '{provenance,is_fallback}'),
      'false'
    ) <> 'true'
);

CREATE VIEW current_opportunity_evaluations
WITH (security_invoker = true) AS
SELECT
  jp.id AS job_id,
  c.id AS company_id,
  c.name AS company,
  c.tier AS company_tier,
  c.enabled AS company_enabled,
  js.id AS source_id,
  js.source_type,
  js.source_key,
  jp.source_job_id,
  jp.canonical_key,
  jp.title,
  jp.locations_json,
  jp.department,
  jp.employment_type,
  jp.description_text,
  jp.source_url,
  jp.posted_at,
  jp.first_seen_at,
  jp.last_seen_at,
  jp.availability_state,
  re.id AS role_evaluation_id,
  re.model_version,
  re.evaluation_json,
  re.created_at AS evaluated_at,
  orev.state AS review_state,
  orev.decision_reason,
  orev.reviewed_at,
  orev.snooze_until
FROM job_postings jp
JOIN companies c ON c.id = jp.company_id
JOIN job_sources js ON js.id = jp.source_id
JOIN opportunity_reviews orev ON orev.job_posting_id = jp.id
JOIN current_calibrated_role_evaluations re ON re.job_posting_id = jp.id;
