-- Stage 1.5 A3 application tracker.
-- Browser writes are RPC-only so creation, calibrated snapshots, and history
-- remain database-enforced invariants rather than UI conventions.

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC;

CREATE TABLE IF NOT EXISTS applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  location TEXT NOT NULL,
  url TEXT,
  stage TEXT NOT NULL DEFAULT 'preparing' CHECK (
    stage IN (
      'preparing',
      'applied',
      'recruiter_screen',
      'interviewing',
      'final_round',
      'offer',
      'rejected',
      'withdrawn'
    )
  ),
  applied_at TIMESTAMPTZ NOT NULL,
  applied_calendar_week SMALLINT NOT NULL CHECK (
    applied_calendar_week BETWEEN 1 AND 53
  ),
  next_action TEXT,
  due DATE,
  contact TEXT,
  salary TEXT,
  notes TEXT,
  source_posting_id INTEGER NOT NULL UNIQUE REFERENCES job_postings(id) ON DELETE RESTRICT,
  eval_snapshot_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS application_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE RESTRICT,
  actor TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  previous_stage TEXT,
  new_stage TEXT NOT NULL,
  CHECK (
    previous_stage IS NULL OR previous_stage IN (
      'preparing',
      'applied',
      'recruiter_screen',
      'interviewing',
      'final_round',
      'offer',
      'rejected',
      'withdrawn'
    )
  ),
  CHECK (
    new_stage IN (
      'preparing',
      'applied',
      'recruiter_screen',
      'interviewing',
      'final_round',
      'offer',
      'rejected',
      'withdrawn'
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_applications_stage_due
  ON applications(stage, due);
CREATE INDEX IF NOT EXISTS idx_application_events_history
  ON application_events(application_id, occurred_at DESC, id DESC);

CREATE OR REPLACE FUNCTION private.record_application_stage_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  event_actor TEXT;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.stage IS NOT DISTINCT FROM NEW.stage THEN
    RETURN NEW;
  END IF;

  event_actor := COALESCE(NULLIF((SELECT auth.jwt() ->> 'email'), ''), current_user);
  INSERT INTO public.application_events (
    application_id,
    actor,
    previous_stage,
    new_stage
  ) VALUES (
    NEW.id,
    event_actor,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.stage END,
    NEW.stage
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION private.prevent_application_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  RAISE EXCEPTION 'application events are immutable';
END;
$$;

CREATE OR REPLACE FUNCTION private.protect_application_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.company IS DISTINCT FROM OLD.company
     OR NEW.role IS DISTINCT FROM OLD.role
     OR NEW.location IS DISTINCT FROM OLD.location
     OR NEW.url IS DISTINCT FROM OLD.url
     OR NEW.applied_at IS DISTINCT FROM OLD.applied_at
     OR NEW.applied_calendar_week IS DISTINCT FROM OLD.applied_calendar_week
     OR NEW.source_posting_id IS DISTINCT FROM OLD.source_posting_id
     OR NEW.eval_snapshot_json IS DISTINCT FROM OLD.eval_snapshot_json THEN
    RAISE EXCEPTION 'application source and evaluation snapshot are immutable';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION private.record_application_stage_event() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION private.prevent_application_event_mutation() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION private.protect_application_snapshot() FROM PUBLIC;

DROP TRIGGER IF EXISTS application_stage_event ON applications;
CREATE TRIGGER application_stage_event
AFTER INSERT OR UPDATE OF stage ON applications
FOR EACH ROW EXECUTE FUNCTION private.record_application_stage_event();

DROP TRIGGER IF EXISTS application_snapshot_immutable ON applications;
CREATE TRIGGER application_snapshot_immutable
BEFORE UPDATE ON applications
FOR EACH ROW EXECUTE FUNCTION private.protect_application_snapshot();

DROP TRIGGER IF EXISTS application_events_immutable ON application_events;
CREATE TRIGGER application_events_immutable
BEFORE UPDATE OR DELETE ON application_events
FOR EACH ROW EXECUTE FUNCTION private.prevent_application_event_mutation();

CREATE OR REPLACE FUNCTION public.mark_application_applied(
  p_job_posting_id INTEGER,
  p_applied_at TIMESTAMPTZ DEFAULT now()
)
RETURNS public.applications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  application_row public.applications%ROWTYPE;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR NOT EXISTS (
    SELECT 1
    FROM public.app_allowed_users allowed
    WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
  ) THEN
    RAISE EXCEPTION 'owner access required' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.applications (
    company,
    role,
    location,
    url,
    stage,
    applied_at,
    applied_calendar_week,
    source_posting_id,
    eval_snapshot_json
  )
  SELECT
    company.name,
    posting.title,
    COALESCE(
      (
        SELECT string_agg(location_value, ' · ' ORDER BY location_index)
        FROM jsonb_array_elements_text(posting.locations_json::jsonb)
          WITH ORDINALITY AS locations(location_value, location_index)
      ),
      'Location not listed'
    ),
    posting.source_url,
    'preparing',
    p_applied_at,
    to_char(p_applied_at AT TIME ZONE 'UTC', 'IW')::SMALLINT,
    posting.id,
    jsonb_build_object(
      'captured_at', now(),
      'role_evaluation_id', evaluation.id,
      'model_version', evaluation.model_version,
      'evaluated_at', evaluation.created_at,
      'evaluation', evaluation.evaluation_json::jsonb
    )
  FROM public.job_postings posting
  JOIN public.companies company ON company.id = posting.company_id
  JOIN public.current_calibrated_role_evaluations evaluation
    ON evaluation.job_posting_id = posting.id
  WHERE posting.id = p_job_posting_id
  ON CONFLICT (source_posting_id) DO NOTHING
  RETURNING * INTO application_row;

  IF application_row.id IS NULL THEN
    SELECT * INTO application_row
    FROM public.applications
    WHERE source_posting_id = p_job_posting_id;
  END IF;

  IF application_row.id IS NULL THEN
    RAISE EXCEPTION 'posting has no current calibrated evaluation'
      USING ERRCODE = 'P0002';
  END IF;

  RETURN application_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.change_application_stage(
  p_application_id INTEGER,
  p_new_stage TEXT
)
RETURNS public.applications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  application_row public.applications%ROWTYPE;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR NOT EXISTS (
    SELECT 1
    FROM public.app_allowed_users allowed
    WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
  ) THEN
    RAISE EXCEPTION 'owner access required' USING ERRCODE = '42501';
  END IF;

  IF p_new_stage NOT IN (
    'preparing',
    'applied',
    'recruiter_screen',
    'interviewing',
    'final_round',
    'offer',
    'rejected',
    'withdrawn'
  ) THEN
    RAISE EXCEPTION 'invalid application stage' USING ERRCODE = '22023';
  END IF;

  UPDATE public.applications
  SET stage = p_new_stage,
      updated_at = now()
  WHERE id = p_application_id
  RETURNING * INTO application_row;

  IF application_row.id IS NULL THEN
    RAISE EXCEPTION 'application not found' USING ERRCODE = 'P0002';
  END IF;

  RETURN application_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_application_details(
  p_application_id INTEGER,
  p_next_action TEXT,
  p_due DATE,
  p_contact TEXT,
  p_salary TEXT,
  p_notes TEXT
)
RETURNS public.applications
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  application_row public.applications%ROWTYPE;
BEGIN
  IF (SELECT auth.uid()) IS NULL OR NOT EXISTS (
    SELECT 1
    FROM public.app_allowed_users allowed
    WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
  ) THEN
    RAISE EXCEPTION 'owner access required' USING ERRCODE = '42501';
  END IF;

  UPDATE public.applications
  SET next_action = NULLIF(btrim(p_next_action), ''),
      due = p_due,
      contact = NULLIF(btrim(p_contact), ''),
      salary = NULLIF(btrim(p_salary), ''),
      notes = NULLIF(btrim(p_notes), ''),
      updated_at = now()
  WHERE id = p_application_id
  RETURNING * INTO application_row;

  IF application_row.id IS NULL THEN
    RAISE EXCEPTION 'application not found' USING ERRCODE = 'P0002';
  END IF;

  RETURN application_row;
END;
$$;

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS owner_read_applications ON applications;
DROP POLICY IF EXISTS owner_read_application_events ON application_events;

CREATE POLICY owner_read_applications ON applications
  FOR SELECT TO authenticated USING (
    (SELECT auth.uid()) IS NOT NULL AND EXISTS (
      SELECT 1 FROM app_allowed_users allowed
      WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
    )
  );

CREATE POLICY owner_read_application_events ON application_events
  FOR SELECT TO authenticated USING (
    (SELECT auth.uid()) IS NOT NULL AND EXISTS (
      SELECT 1 FROM app_allowed_users allowed
      WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
    )
  );

REVOKE ALL ON applications FROM anon, authenticated;
REVOKE ALL ON application_events FROM anon, authenticated;
GRANT SELECT ON applications TO authenticated;
GRANT SELECT ON application_events TO authenticated;

REVOKE ALL ON FUNCTION public.mark_application_applied(INTEGER, TIMESTAMPTZ)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.change_application_stage(INTEGER, TEXT)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.update_application_details(
  INTEGER, TEXT, DATE, TEXT, TEXT, TEXT
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.mark_application_applied(INTEGER, TIMESTAMPTZ)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.change_application_stage(INTEGER, TEXT)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_application_details(
  INTEGER, TEXT, DATE, TEXT, TEXT, TEXT
) TO authenticated;
