-- Stage 1.5 B-30: durable owner-gated web intake queue.
-- The web records intent; the existing Python scanner owns fetch, parse, gates,
-- evaluation, and destination transitions so scoring has one implementation.

CREATE TABLE IF NOT EXISTS manual_intake_submissions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_email TEXT NOT NULL,
  intake_mode TEXT NOT NULL CHECK (intake_mode IN ('url', 'text', 'manual')),
  source_url TEXT,
  jd_text TEXT,
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  location TEXT,
  note TEXT,
  destination TEXT NOT NULL CHECK (
    destination IN ('potential_matches', 'to_apply', 'applied')
  ),
  propose_watchlist BOOLEAN NOT NULL DEFAULT false,
  status TEXT NOT NULL CHECK (
    status IN ('queued', 'processing', 'needs_text', 'manual_unscored', 'completed', 'failed')
  ),
  job_posting_id INTEGER REFERENCES job_postings(id) ON DELETE SET NULL,
  error_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (intake_mode <> 'url' OR source_url ~* '^https?://'),
  CHECK (intake_mode <> 'text' OR length(btrim(COALESCE(jd_text, ''))) >= 120)
);

CREATE INDEX IF NOT EXISTS idx_manual_intake_queue
  ON manual_intake_submissions(status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_manual_intake_destination
  ON manual_intake_submissions(destination, status, created_at DESC);

ALTER TABLE manual_intake_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_intake_submissions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS manual_intake_owner_select ON manual_intake_submissions;
CREATE POLICY manual_intake_owner_select
ON manual_intake_submissions
FOR SELECT
TO authenticated
USING (
  lower(owner_email) = lower((SELECT auth.jwt() ->> 'email'))
  AND EXISTS (
    SELECT 1 FROM app_allowed_users allowed
    WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
  )
);

REVOKE ALL ON TABLE manual_intake_submissions FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE manual_intake_submissions TO authenticated;

CREATE OR REPLACE FUNCTION public.submit_manual_intake(
  p_intake_mode TEXT,
  p_company TEXT,
  p_title TEXT,
  p_location TEXT DEFAULT NULL,
  p_source_url TEXT DEFAULT NULL,
  p_jd_text TEXT DEFAULT NULL,
  p_note TEXT DEFAULT NULL,
  p_destination TEXT DEFAULT 'potential_matches',
  p_propose_watchlist BOOLEAN DEFAULT false
)
RETURNS public.manual_intake_submissions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  submission public.manual_intake_submissions%ROWTYPE;
  owner_email TEXT := lower(COALESCE((SELECT auth.jwt() ->> 'email'), ''));
  mode TEXT := lower(btrim(COALESCE(p_intake_mode, '')));
  destination TEXT := lower(btrim(COALESCE(p_destination, '')));
BEGIN
  IF (SELECT auth.uid()) IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.app_allowed_users allowed
    WHERE lower(allowed.email) = owner_email
  ) THEN
    RAISE EXCEPTION 'owner access required' USING ERRCODE = '42501';
  END IF;
  IF mode NOT IN ('url', 'text', 'manual') THEN
    RAISE EXCEPTION 'invalid intake mode' USING ERRCODE = '22023';
  END IF;
  IF destination NOT IN ('potential_matches', 'to_apply', 'applied') THEN
    RAISE EXCEPTION 'invalid intake destination' USING ERRCODE = '22023';
  END IF;
  IF length(btrim(COALESCE(p_company, ''))) NOT BETWEEN 1 AND 200
     OR length(btrim(COALESCE(p_title, ''))) NOT BETWEEN 1 AND 300 THEN
    RAISE EXCEPTION 'company and title are required' USING ERRCODE = '22023';
  END IF;
  IF mode = 'url' AND COALESCE(p_source_url, '') !~* '^https?://' THEN
    RAISE EXCEPTION 'URL intake requires http(s)' USING ERRCODE = '22023';
  END IF;
  IF mode = 'text' AND length(btrim(COALESCE(p_jd_text, ''))) < 120 THEN
    RAISE EXCEPTION 'JD text must contain at least 120 characters' USING ERRCODE = '22023';
  END IF;
  IF length(COALESCE(p_note, '')) > 4000 THEN
    RAISE EXCEPTION 'note is too long' USING ERRCODE = '22001';
  END IF;

  INSERT INTO public.manual_intake_submissions (
    owner_email, intake_mode, source_url, jd_text, company, title, location,
    note, destination, propose_watchlist, status
  ) VALUES (
    owner_email,
    mode,
    NULLIF(btrim(p_source_url), ''),
    NULLIF(btrim(p_jd_text), ''),
    btrim(p_company),
    btrim(p_title),
    NULLIF(btrim(p_location), ''),
    NULLIF(btrim(p_note), ''),
    destination,
    p_propose_watchlist,
    CASE WHEN mode = 'manual' THEN 'manual_unscored' ELSE 'queued' END
  )
  RETURNING * INTO submission;
  RETURN submission;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_manual_intake(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.submit_manual_intake(
  TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN
) TO authenticated;

-- Trusted scanner connections have the database credential, not an end-user JWT.
-- Browser creation remains RPC-only; allow the scanner to complete an evaluated
-- submission into the application tracker without weakening browser RLS.
CREATE OR REPLACE FUNCTION private.close_shortlist_on_application()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF (SELECT auth.uid()) IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.app_allowed_users allowed
    WHERE lower(allowed.email) = lower((SELECT auth.jwt() ->> 'email'))
  ) THEN
    RAISE EXCEPTION 'owner access required' USING ERRCODE = '42501';
  END IF;

  UPDATE public.opportunity_reviews
  SET state = 'approved', decision_reason = NULL, reviewed_at = now()::TEXT, snooze_until = NULL
  WHERE job_posting_id = NEW.source_posting_id
    AND state = 'interested';
  RETURN NEW;
END;
$$;
REVOKE EXECUTE ON FUNCTION private.close_shortlist_on_application() FROM PUBLIC;
